### ISSUE TITLE
Remove zoom boutons

### ISSUE THREAD

**Issue by gregory-lebl** [pavel-corsaghin/react-native-leaflet#30]
Hello,
Can we remove the buttons at the top left that allow us to zoom in? I want my user to use the pinch to zoom in and out.

I see that there are no ZoomControl props so I'm asking.

Thank you for your answer.

Have a nice day.

**Comment by miallo** [comment]
I know it is a bit late, but no - with the current state of the library this is not possible, since it is hardcoded in the HTML blob. In our company we have patched the HTML to remove the ZoomControl and eventually we want to publish a very much stripped down version of this lib, but unfortunately we are not quite there yet...

**Comment by gregory-lebl** [comment]
Hello,

Thanks for the reply.

Have a nice day. 😄
